src/Server/BodySculptor.Administration/Controllers/ArticlesController.cs
namespace BodySculptor.Administration.Controllers
{
    using BodySculptor.Administration.Models.Articles;
    using BodySculptor.Administration.Services.Interfaces;
    using BodySculptor.Common.Infrastructure;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    [AuthorizeAdministrator]
    public class ArticlesController : AdministrationController
    {
        private readonly IArticlesService articlesService;

        public ArticlesController(IArticlesService articlesService)
        {
            this.articlesService = articlesService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var articles = await this.articlesService
                .GetArticles();

            return this.View(articles.Content);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateArticleInputModel model)
        {
            var result = await this.articlesService
                .CreateArticle(model);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string articleId)
        {
            await this.articlesService
                .DeleteArticle(articleId);

            return RedirectToAction(nameof(Index));
        }
    }
}

src/Server/BodySculptor.Administration/Controllers/ExercisesController.cs
namespace BodySculptor.Administration.Controllers
{
    using BodySculptor.Administration.Models.Exercises;
    using BodySculptor.Administration.Services.Interfaces;
    using BodySculptor.Common.Infrastructure;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    [AuthorizeAdministrator]
    public class ExercisesController : AdministrationController
    {
        private readonly IExercisesService exercisesService;

        public ExercisesController(IExercisesService exercisesService)
        {
            this.exercisesService = exercisesService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var exercises = await this.exercisesService
                .GetExercises();

            return this.View(exercises.Content);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var muscleGroups = await this.exercisesService
                .GetMuscleGroups();

            ViewData["muscleGroups"] = muscleGroups.Content;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateExerciseInputModel model)
        {
            var result = await this.exercisesService
                .CreateExercise(model);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string exerciseId)
        {
            var exerciseToEdit = await this.exercisesService
                .GetExerciseById(exerciseId);

            var muscleGroups = await this.exercisesService
                .GetMuscleGroups();

            ViewData["ExerciseDto"] = exerciseToEdit.Content;
            ViewData["muscleGroups"] = muscleGroups.Content;

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditExerciseInputModel model)
        {
            //TODO: Fix secondaryMuscleGroups binding
            string exerciseId = RouteData.Values["Id"].ToString();

            var result = await this.exercisesService
                 .EditExercise(exerciseId, model);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string exerciseId)
        {
            await this.exercisesService
                .DeleteExercise(exerciseId);
    
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Server/BodySculptor.Administration/Controllers/IdentityController.cs
namespace BodySculptor.Administration.Controllers
{
    using BodySculptor.Administration.Models.Identity;
    using BodySculptor.Administration.Services.Interfaces;
    using BodySculptor.Common.Constants;
    using BodySculptor.Common.Infrastructure;
    using BodySculptor.Services.Mapping;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading.Tasks;

    public class IdentityController : AdministrationController
    {
        private readonly IIdentityService identityService;

        public IdentityController(IIdentityService identityService)
        {
            this.identityService = identityService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return this.View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginFormModel model)
        {
            return await this.Handle(
                async () =>
                {
                    try
                    {
                        var loginModel = model.MapTo<UserInputModel>();

                        var result = await this.identityService
                        .Login(loginModel);
                        this.Response.Cookies.Append(
                        InfrastructureConstants.AuthenticationCookieName,
                        result.Content.Token,
                        new CookieOptions
                        {
                            HttpOnly = true,
                            Secure = false,
                            MaxAge = TimeSpan.FromDays(1)
                        });
                    }
                    catch (Exception ex)
                    {
                        ;
                        throw;
                    }
                },
                success: RedirectToAction(nameof(HomeController.Index), "Home"),
                failure: View("../Home/Index", model));
        }

        [AuthorizeAdministrator]
        public IActionResult Logout()
        {
            this.Response.Cookies.Delete(InfrastructureConstants.AuthenticationCookieName);

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

src/Server/BodySculptor.Administration/Controllers/NutritionController.cs
namespace BodySculptor.Administration.Controllers
{
    using BodySculptor.Administration.Models.Foods;
    using BodySculptor.Administration.Services.Interfaces;
    using BodySculptor.Common.Infrastructure;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    [AuthorizeAdministrator]
    public class NutritionController : AdministrationController
    {
        private readonly INutritionService nutritionService;

        public NutritionController(INutritionService nutritionService)
        {
            this.nutritionService = nutritionService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var foods = await this.nutritionService
                .GetFoods();

            return View(foods.Content);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var foodCategories = await this.nutritionService
                .GetFoodCategories();

            ViewData["foodCategories"] = foodCategories.Content;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateFoodInputModel model)
        {
            var result = await this.nutritionService
                .CreateFood(model);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var foodForEditDto = await this.nutritionService
                .GetFood(id);
            var foodCategories = await this.nutritionService
                .GetFoodCategories();

            ViewData["foodDto"] = foodForEditDto.Content;
            ViewData["foodCategories"] = foodCategories.Content;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UpdateFoodInputModel model)
        {
            string foodId = RouteData.Values["Id"].ToString();

            var result = await this.nutritionService
                 .EditFood(foodId, model);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            await this.nutritionService
                .DeleteFood(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

src/Server/BodySculptor.Administration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BodySculptor.Administration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (this.User.IsAdministrator())
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BodySculptor.Administration</a>
                    <a class="float-left" asp-area="" asp-controller="Exercises" asp-action="Index">Exercises</a>
                    <a class="float-left" asp-area="" asp-controller="Nutrition" asp-action="Index">Foods</a>
                    <a class="float-left" asp-area="" asp-controller="Articles" asp-action="Index">Articles</a>
                    <a class="float-right" asp-area="" asp-controller="Identity" asp-action="Logout">Logout</a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BodySculptor.Administration</a>
                }
                <button class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BodySculptor.Administration - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>